# Seminars at Cardiff University

One of the perks of working at a university is that you are expected to spend some of your time developing your interests and participating in university life. You are encouraged to attend seminars whenever something that interests you is on offer. You may want to keep the times of these regularly-occurring seminars free during term time.

* School of Psychology Colloquium: some Fridays from 16:00-17:00, usually in 5th floor common room of the Tower building
* Cardiff's branch of the UK Reproducibility Network: Join the mailing list (https://intranet.cardiff.ac.uk/staff/get-involved/groups-and-networks/view/reproducibility-network) and watch for announcements. (Note -although my name is on this I'm no longer responsible for it and I have no idea whether the current staff running this are planning anything soon.) 
* Cognitive Development Group: some Thursday afternoons. If interested, request to join the CogDev group on Teams, currently managed by Rhys Davies (daviesrm19@cardiff.ac.uk).
* CURBIC Seminar: Mondays, 12:00-13:00, CUBRIC Seminar Room 2. Watch for emails, sometimes this meeting takes place from 16:00-17:00 instead
* Cognitive Neuroscience, first Friday of the month, 12:00-13:00, in CUBRIC Seminar Room 2
* CUCHDS (developmental) seminar: Third Thursday of the month, 13:00-14:00, in CUCHDS seminar room (1st floor)


