# Student projects we support at Cardiff University

## Postgraduate researchers

### PhD projects

We currently consider applications for PhD projects. One line, to work on a PhD project based on the PI's main research interests, is currently available. The successful candidate would begin in October 2019. Two ideas for projects are on offer, but it is likely that only one candidate, working on one of these projects, may be funded. This position is only available to students with access to local fees (e.g., UK/EU residents). 

**Explaining interference in working memory**: Morey has demonstrated that visual information is fragile, and is disrupted by many kinds of cognitive tasks, not only visual or spatial tasks (see Morey (2018) for a summary of the evidence). This contrasts with verbal information: there is a lot of robust evidence that verbal information may be maintained nearly as well when doing an irrelevant non-verbal task as when focusing only on the verbal memory task. The successful candidate will work with the PI to design a series of experiments comparing alternative explanations for this pattern, and delineating the boundary conditions of this pattern to better inform theory. The candidate will have access to preliminary pilot data to jump-start his or her work.

**Maintenance of spatial information, with and without intent**: Memory for novel, arbitrary collections of spatial locations appears to be much more limited than memory for verbal information. Yet some evidence suggests that spatial information of verbal labels or visual content is autmatically encoded and maintained at least for a short period. The successful candidate will apply new electrophysiological methods, using scalp alpha readings to infer which spatial locations are maintained, to compare spatial location memory under a variety of circumstances. The successful candidate will work with the PI to design a series of experiments comparing alternatives. The candidate will have access to preliminary pilot data to jump-start his or her work.

This opening is funded by the School of Psychology. Details on how to apply will be available in late 2018 or early 2019. The School of Psychology expects candidates to have minimally a 2:1 Bachelor's degree. Realistically, short-listed candidates for School-funded PhDs tend to have a first-class degree (either Bachelor's or Master's, or both). The basic position is a 3-year funded PhD, but exceptional candidates will be considered for a Graduate Teaching (GTA) position. GTAs perform light UG instruction alongside their PhD work and receive increased funding for 4 years.

There is also an opportunity to undertake a PhD in meta-scientific research, supervised jointly by Dr. Candice Morey and Prof. Chris Chambers. See our [advert](https://www.findaphd.com/search/ProjectDetails.aspx?PJID=100639) for details.

There are other routes to funding a PhD that prospective students may also explore. Cardiff University offers limited funding for international student fee waivers and stipends. Some opportunities are general, apply to students from anywhere in the world, and there are some scholarships available to prospective students from particular countries. 

Several UK funding agencies (including Wellcome, ESRC, and Leverhulme) offer PhD studentships. These opportunities tend to be student-led: the student is expected to write the proposal and application. Even so, it is a big advantage to have the advice and assistance of the potential supervisor in crafting an application for a PhD scholarship. Dr. Morey will assist excellent prospective students with applications provided that 1) the research proposed aligns closely with her research interests, 2) the student demonstrates capability to carry out a PhD project (e.g., has a strong prior academic record, strong communication skills, and excellent references from previous mentors), and 3) the prospective student makes contact in enough time to develop and prepare the proposal ahead of the funder's deadline. (Note: "in time" for something like this is, realistically, at least a full month before anything needs to be submitted.)

### DEdPsy, Educational Psychology

Some of the developmental work we do could serve to support the research training of DEdPsy students. Please get in touch with Dr. Candice Morey if you are interested in hearing about project opportunities and discussing the educational relevance of our basic memory research. 

### Taught MSc student projects

We are happy to host students taking part in the **Neuroimaging Methods and Applications**, **Children's Psychological Disorders**, and **Social Science Research** MSc degrees. Appropriate project suggestions will be available annually. Feel free to get in touch with Candice Morey to discuss ideas.

## Undergraduate researchers

### Final year UG projects

Every year we host final year UG projects. A selection of project descriptions are available in the course handbook every spring. Upon joining the lab, students receive an updated list of opportunities for projects. Note though that some projects require the participation of mulitple student researchers. Choice of project is always a function of both logistic contraints and student preference.


### Professional placements

In some years, we may have the capacity to offer a professional placement to students on a Psychology with Professional Placement course. These positions will be advertised at eligible institutions. Interested students may enquire if they do not see an advertisement in their programme; we may possibly be able to accomodate a placement student even if we have not advertized. 

Our placement will be entirely research-focused. This may not fulfill the requirements of all placement programmes.

### CUROP and SPRINT summer research projects

Cardiff University and the School of Psychology offer funded summer internships for current students. Interested students should get in touch with Dr. Morey as early as possible in the spring. Project descriptions will be available in the spring.

## Pre-university students

### Nuffield summer intern placements

We are willing to offer research experiences to teenagers interested in learning about cognitive and developmental psychology some summers. When we have an opening, we will list it in the relevant places.






