# Lab spaces we use

We do basic cognitive research with young adults and children as participants. Sometimes we make use of special equipment (e.g., eye trackers, EEG). These needs mean we have a stake in several laboratory spaces within the School of Psychology.

## 64 Park Place, room 0.05

This lab is available for use by anyone in the School of Psychology, but in practice it is used mainly by us. The room contains two sound-attenuated chambers with work stations both inside and outside the chambers. Priority for using this space: studies with adult participants in which participants must run singly, and for which noise reduction is very important. (This describes most of our research.)

### Access to 64 PP 0.05

Request swipe-card access from the PI, who will forward your request to psychlocks@cardiff.ac.uk.

### Security in 64 PP 0.05

64 PP is only accessible to personnel with swipe-card access. The Cardiff University Film Unit is based there, several staff have their offices there, and many PhD student's desks are in the building. During regular working hours, there should always be people around to help in case of an emergency. Note the signs indicating fire escape routes and current first aiders.

As with any building that has restricted access, you should not allow anyone to follow you in when you enter, and you should not admit someone requesting to enter if you do not know who they are and what they are there for. 

### Booking 64 PP 0.05

Whether you are programming your study, pilot-testing your study, or running participants, you need to schedule any work time in 64 PP 0.05 or risk being kicked out because another person scheduled it properly. 

We maintain an Outlook calendar for this lab so that you may conveniently book it. You may request access to the calendar from the PI. Once granted access, you will be able to view and edit the calendar "64 Park Place 0.05" from your university MS Outlook account. 

In general, you may book the lab any time it is apparently free. But do keep in mind that other people may need to use it too, especially during peak participant-running times. 

We want to always faciliate efficient use of the space. Please consider the following when booking:

- You should make separate reservations per booth so that we can tell if both or only one booth is in use at a particular time.

- Don't "block-book" the booths to run particpants for a long period (i.e., a whole day). You may actually use the room for a long period like a whole day, but make a separate reservation in the calendar for each discrete event (e.g., a 1.5-hour session with a participant). This way, if some of your bookings are not taken or cancelled, you can update the calendar so that the rest of us can see if there are times when the booths might be free. 

- Besides the date and time, your reservation should include your name, and information about what you are doing (e.g., "participant", "programming", etc.), and which booth you are reserving. This information helps other users know whether they may be able to step in during the booking, and in the event of a mis-communication about scheduling, helps prioritize.

- If booths somehow become over-committed, priority will go to running scheduled participants over programming or preparing. During peak times, plan to do any programming or preparing somewhere else, and when you need to use the lab to install your programs and test them, plan to do that during a time that is inconvenient for participant testing.

### Peak usage

The lab will be busiest during term times. That's mid October until mid December, mid-January until Easter break, during the regular work day (e.g., 9:30 - 16:30). Whenever possible, do not plan on having access to the lab for programming during peak times. During peak times, the best times to use the lab for preparing a protocol, installing programs, or retrieving data are early in the morning (e.g., before 9:30) and during times when both Year 1s and Year 2s have lectures. For Autumn 2018, that's Thursdays and Fridays from 10:00-11:00. For Winter 2019, there is no overlap in their timetables.

### Storage

There are shelves in the lab which you may use to store things that you use while in the lab (e.g., experimental paperwork, notebooks, etc.). Bring some sort of container to keep your things in, and label it with your name. After you complete a study, you should remove the paperwork associated with that study from the lab. Please do not leave personal items in the lab after you are finished working there. When you are no longer collecting data for the lab or working in 0.05 regularly, remove the things you have stored there. The contents of the shelves will be periodically binned to avoid clutter, and anything associated with a former lab member that's left behind will be binned or appropriated by someone else. 

## CUCHDS

http://psych.cf.ac.uk/cuchds/

## Laboratories in CUBRIC

### EEG

http://www.cardiff.ac.uk/cardiff-university-brain-research-imaging-centre/facilities/electroencephalography-labs

### EyeLink

http://www.cardiff.ac.uk/cardiff-university-brain-research-imaging-centre/facilities/cognitive-testing-labs



