# Ethics at Cardiff School of Psychology

Ethical approval is an essential part of conducting research. At Cardiff University, each academic school has its own School Research Ethics committee (SREC) that is responsible for ensuring that all research carried out within the School has been subject to an ethical review. The university's procedure for ethical review allows staff and students to achieve research excellence and produce work with the highest standards of research integrity and professionalism.

## Who needs to apply?

Staff and students conducting research on humans must apply for ethical approval. In some cases, ethical approval may have been granted by an external organisation (e.g., NHS) and this approval letter must be submitted to the SREC. 

You may not need a completely new application if your research project fits under one of the lab approvals already in place. Speak with your supervisor early in your project to determine what you must do to ensure your work is covered by ethics approval. Even if you do not need to make a new application to the ethics committee, you likely need to complete some training and have a conversation about ethics with the staff member supervising your research before you are allowed to begin.

## How to apply for ethical review?

A great starting point for information and resources about the ethical review process can be found at [InsidePsych](https://inside.psych.cf.ac.uk/). Log in with your Cardiff University credentials and navigate to the _**Ethics**_ tab which can be found in the Undergraduate, Postgraduate, and Staff pages. 

## Mandatory Research Integrity Training

All researchers must complete the Cardiff University Research Integrity Training module. PGRs and staff members should automatically find this as an enrollment on their Learning Central page. UGRs can access it [here](https://intranet.cardiff.ac.uk/staff/training-and-development/staff-courses-and-programmes/research-careers/training/research-integrity-online-training-programme).

### Types of applications 

All applications and supporting documents must be emailed to the Ethics committee at psychethics@cardiff.ac.uk 

**1. Proportionate applications:** This procedure is used for proposals that do not raise any ethical issues and recruits participants from the School's participant panel. To recruit from the panel, you will need to sign up for a researcher account on the School of Psychology's [Experimental Management System](https://cardiff.sona-systems.com/Default.aspx?ReturnUrl=/) and obtain ethical approval before you begin recruiting participants. Proportionate applications can also be used to make minor amendments to a project that has been previously approved. These applications must be submitted by midday on a Friday and a decision will be made within 7-10 days.

**2. Full applications:** These applications require more detailed descriptions of the experimental procedures, research design, and ethical considerations. Full applications must be submitted at least two weeks before the Ethics Committee's next meeting. The committee usually meets on the first Tuesday of every month.

Full applications are used when a research project involves (a) recruiting special groups of participants (e.g., children, people in custody, those lacking capacity to give consent, or people engaged in illegal activities); (b) highly sensitive topics (e.g., domestic violence, terrorism, etc), (c) the use of a drug (e.g., tobacco, caffeine, or alcohol), (d) the collection or use of human tissue, or (e) the preservation of personal data (e.g., personal identifiable information stored with data, voice or image recordings, etc.). In essence, if the research poses an ethical consideration, a full application must be submitted for review.

**3. Generic applications:** Sometimes, researchers may have a range of studies they would like to conduct within a research paradigm. In these cases, a generic application can be completed so long as there is sufficient description of the different studies they wish to undertake.

For example, a researcher may want to study the effectiveness of recall in different situations. A generic application can be submitted so long as the different studies within this paradigm are described, for example, testing memory in a noisy environment or after participants have had a cup of coffee. Depending on the ethical considerations in the study, these applications may either be a fast track or full application. **Undergraduate students are not permitted to apply for generic approval.**

**4. Amendments to approved projects:** Sometimes, changes may be made to a project that already has ethical approval. If they are changes to the research team or the project end date then send an email to the Ethics Committee with the details of the change and the project's ethics reference number. All other changes require the submission of a new ethics proforma along with the previous ethics reference number for the project. Remember to provide sufficient detail about the changes as if they are minor amendments they will be dealt with through the fast track route while if they are major changes they will be considered in the same way as a full proposal.

## What forms will I need to complete?

### Ethics proforma

An ethics proforma must be completed for all applications except those seeking approval for minor amendments. The proforma can be downloaded [here](https://inside.psych.cf.ac.uk/). You will also find guidance notes for the proforma on this page. The proforma asks for details about your study - who is conducting it, who are the participants, and what methods will be employed. If you are conducting a project with no foreseeable ethical considerations then your application will be considered under the proportionate route. If you are conducting a project that raises ethical considerations then you will need to include additional details and materials for review.

### Risk assessment

Risk assessments are a mandatory part of the ethical review process. When you fill in the proforma, you will also be prompted to complete an online risk assessment form. There may already be a risk assessment in place for the lab facility you are using and if your project does not add any new procedure to that assessment, you might be able to use the existing risk assessment number for your proposal. Speak with the manager of the lab space to determine whether your project requires a fresh risk assessment. Even if it does not, you must familiarize yourself with the existing risk assessment.

If you do need to complete a new risk assessment, there is a link in the proforma to the online instrument that begins this process. This instrument is designed to provide an overall estimate of the risk involved in the project and who is likely to be affected. You will be asked to rate, on a scale of 1 to 5, the likelihood of a hazard causing a problem and the severity of injury resulting from the hazard. For example, equipment like computers may pose a risk of electric shock, however, with control measures like PAT testing the likelihood of electric shocks may be low (rated as 1 - very unlikely) while the severity may be rated as 3 to indicate that an electric shock may lead to some temporary injuries. Once you have completed and submitted the form, you will receive an email to indicate if a full risk assessment is needed. If so, the email will also contain a link for the full risk assessment form, guidance notes, and details for where to send the completed form. You will have to give information about the hazard, measures to mitigate its impact, and ratings for the likelihood and severity of the hazard. **Please note you cannot submit your ethics application to the committee before you have a valid risk assessment number.** When planning an application that requires a new risk assessment, assume that you will be asked to revise your risk assessment based on feedback, which may take a few extra days. Once your risk assessment is approved, you will receive a unique *Risk assessment receipt number* via email. You must include this receipt number in your Ethics Proforma when you submit (your application will be returned to you if this information is not included).

You can now submit your ethics proforma together with any supporting documents for ethical review! **Remember, you CANNOT begin any research activities with participants until your application has been approved by the Ethics Committee.**