
# Dealing with the unexpected during data collection

We design experimental materials to be easily administered and as fail-safe as possible. However, that doesn't mean that nothing can go wrong during your data collection. Here is a description of how participant running usually goes, and then anecdotal exceptions that have occurred to us more than once.

## The slow participant

Most student participants are not new to taking part in research, and understand the drill. They want to get in and out of a session as quickly as possible. This is so typical that we must account for it in the design of experiments and ensure that participants learn that they will not benefit from random responding. However, some participants take much longer than is typical to respond. Sometimes, we never learn why, we simply see that their session takes a long time and their response speeds are much slower than average. Sometimes, these participants wish to discuss how they are doing the task in detail with the experimenter. If a participant wants to discuss the experiment with you, always engage with them as far as possible (up to explaining the hypothesis, which you can do after they finish).

## The inattentive participant

Remember how most student participants have learned that it is in their best interest to finish as quickly as possible? Some will try to speed everything along: they will grab the mouse and start trying to enter information without knowing what they are doing, will start mashing SPACE, ENTER and random keys to get the study going. Data from this behavior would not signify anything. This is the reason our policy is always to personally explain instructions and have a supervised practice session. Practice sessions should be designed so that the experimenter is certain the participant understands the task, and that the participant is not inadvertently rewarded for speeding through examples and instructions. 

Sometimes we cannot ensure that a participant will not choose to randomly respond after they are left on their own. Our tasks are often hard, and it would not always be reasonable to impose an accuracy criterion (though sometimes it is). Our strategy is to ensure that they know how to do the task, not to set it up in such a way that non-responding would allow them to finish earlier, and to build in some trials that are meant to detect insincere attempts. Usually, this means including some very easy condition. Even if these trials are not meant to be part of the main design, they can be used to check that the participant understood what to do and was not responding randomly.

## Sleepy, sick, or inebriated participants

Student life is difficult, and sometimes you will greet a participant who isn't in fit condition to be working on anything. The PI has seen participants who came over directly from the pub, who were so ill that they ought to have been in bed, or who were so tired they could hardly sit up. These participants are trying too hard to meet their requirements. If you encounter a participant in this state, the best option is to offer to reschedule them. They will not learn anything from trying to take part.

## The participant with a lot of questions

Occasionally, a participant will want to know a lot of detail about how the study works or what will be done with the data. Intellectual curiousity is always to be encouraged. Engage with questions as best you can, but if you do not feel up to answering all of them, refer the participant to the PI or another senior, responsible researcher. 

Often these participants want to see their own data. Our general policy is only to release anonymized data sets. Note down this participant's email address so that we can alert him or her when the anonymized data are available. In some cases, we may be okay with giving the participant their own data set as well. The reason that we generally do not do this is that in our experimental tasks, usually there is little (if anything) to be learned from one person's performance. There is nothing diagnostic we would be able to say about certain task scores, and there is some worry that a participant might try to read too much into their performance. Giving access to the anonymized data would be sufficient to let them have a go at data analysis and satisfy their curiosity about the results. 

# Tips and tricks for working with children

So you want to run a developmental study and work with children. There are several things which need to be considered when designing and conducting a developmental study.  

## Designing an experiment for children

Firstly, all developmental studies should be given a cover story and gamified to the extent possible. Unlike adult participants who will tolerate (to some extent) a task in which they are just instructed what to do, children have a much lower attention threshold and will quickly get bored of completing a task if all they are given to look at is a white screen with some black shapes (for example). It is worth noting that children will have a shorter attention span than adults, and younger children will have an even shorter attention span than older children and that their attention span will be decreasing through every aspect of the session (e.g., any preliminary set-up or questions), so it is important that there is also a limited delay in starting the essential tasks you need them for. 

When designing a developmental experimental paradigm consideration should be given to the types of equipment to be used during the experiment given what you are thinking of investigating. For example, many primary school aged children are now commonly exposed to touchscreen tablets and may not have used a computer mouse before, so if you are thinking of investigating reaction times it would be important to have children respond on a touchscreen, as they may struggle to answer promptly using a computer mouse, thus invalidating the response times calculated. CUCHDS has a wide range of furniture and equipment which is suitable for children to use and it is recommend to discuss with your PI what equipment may be available for you to use.  

The length of study should be as short as possible, whilst also enabling the collection of the minimum amount of required data. It is useful when designing the study to work out what the minimum number of trials to be conducted for each condition should be and then add some additional trials to the task as it is likely that trials will need to be excluded during data analysis because children will often move around/get distracted whilst completing the task, potentially leading to data which is messy and does not accurately represent the behavior you are investigating. Therefore having spare trials can help to mitigate the amount of data that may be lost. Additionally, putting the most important task for the research at the start of the experimental session is wise to ensure that the children are most attentive and engaged when completing the task. Tasks which are of lower importance should be placed at the end of the session when the children are more likely to be bored and more easily distracted or inattentive. To make it worthwhile for parents to come to the CUCHDS centre most studies for children aged 5-years-old and older tend to last around one hour, including the signing of consent forms and breaks, and most studies will not last over two hours maximum as children will not typically concentrate for longer than this (studies over one hour will often include neurophysiological measures which take time to set up with the child, e.g. EEG capping).  

When planning the session structure it’s useful to decide on points during the experiment when breaks can be taken to limit the amount of disruption to the task. Children should be informed before the session that they can take breaks and should let the research know when they would like to take a break. When break points are reached during the experiment session the researcher should inform the child that they can take a break if they would like to or continue to play the games. It is often helpful to plan for breaks when switching between tasks and not during a task to minimize disruption during a task, unless the child is completing one continuous task throughout the session.  

To help with continued engagement in the task, it can be useful to provide the children with praise and encouragement. For example, informing them every few trials that they are ‘doing well’, doing a ‘good job’ etc. If the children believe they are doing well at the game this can help them to concentrate and continue to try their best. Another form of encouragement is giving the child a sticker when milestones are achieved during the session, e.g. after completing one game and before moving onto the next game.   

As a thank you for taking part the children are given a prize (e.g., a small toy), stickers and a certificate of participation. It is also possible to give a small cash honorarium to the parents for taking part as well, but this is often only the case when the parent is required to also take part in the research as a participant or in infant studies. It is also possible to cover transportation costs for parents to travel to CUCHDS, but it is common for most studies to only offer free parking outside of CUCHDS for the duration of the study session for families traveling by car.  

## On the day considerations

Some elements to consider when conducting research with children is whether the parent will be required to sit in the experiment room throughout the session. Sometimes (especially during school holidays) parents will bring siblings along to the testing sessions as they don’t have other childcare arrangements or they have something else planned for after the session. It is important to consider this when inviting children to take part if the parent needs to be present with the child during the experimental task. If the parent needs to be present in the research room throughout the session, then another member of the research team should be available to sit in the waiting area with the sibling not taking part to help ensure that the participating child is not distracted by their sibling. Another option is to ask both parents (or for another adult) to attend the session so that one adult can wait in the waiting area, however this will make it more difficult to book in child participants as it can be difficult for families to facilitate this. When inviting parents it is good practice to let them know whether a parent/adult will be required to stay with the child partaking in the research or whether they will wait in the waiting area so that families know in advance of the session what is required.   

For some families and children taking part in research might be the first time they have visited a university campus and as such it is important to remember that children and parents may be nervous or anxious when attending. As such, it is key that the researchers present themselves in a friendly manner and take time to explain what is going to happen during the research session and what the different rooms are when moving families around the building. One way in which the children and parents anxiety can be alleviated is by showing the child and parent where the research will be conducted (i.e. in which testing room) and how close it is to the waiting area. It may also be advisable to familiarise the child and parent with the equipment, which is going to be used in the research, especially if the equipment being used is likely to be something which they may not have come across before e.g. EEG cap and electrodes, eye tracker, etc.  

It is advisable that for older children (5-years-old and up) that parents are asked to wait in the waiting area or observation room during the testing session so that the child is not distracted. Sometimes children will look to their parents for help or get distracted by the parent being in the room, which could affect the data. However, sometimes the child and/or parent is not comfortable with this and will request for the parent to stay in the room during the research session. If this is the case make sure that there is a chair available for the parent and ask the parent not to distract or help the child complete the task as we want to investigate how the child completes the task. The child should also be reminded that the parent is not able to help them complete the task and that we want to see how well they (the child) can play the games. 

